; platformio.ini file for RDCP-Quad-Relay

[env:roloran_quad_board]
platform = espressif32 @ 6.12.0
platform_packages = tool-esptoolpy@https://github.com/pioarduino/esptool/releases/download/v4.8.11/esptool.zip
board = esp32-s3-devkitc-1
; board.mcu = esp32s3
framework = arduino
#build_flags = 
#  -D ARDUINO_USB_MODE=1
#  -D ARDUINO_USB_CDC_ON_BOOT=1
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_filters = send_on_enter
lib_deps = 
	jgromes/RadioLib@^7.6.0
	rweather/Crypto@^0.4.0
	https://github.com/roloran/SchnorrSig
	https://github.com/roloran/Unishox_Arduino_lib
  avinabmalla/ESP32_BleSerial@^3.0.0
